services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: harapan
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db_harapan
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_harapan
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  db_data:
